/* Allegro datafile object indexes, produced by grabber v4.2.0, MSVC.s */
/* Datafile: c:\Users\hp\Desktop\Juego Build 3.7\Juego Build 3.0.2\datos_del_juego.dat */
/* Date: Tue Dec 03 12:32:06 2019 */
/* Do not hand edit! */

#define dftextos                         0        /* FONT */
#define dibosque                         1        /* BMP  */
#define dibosquechoque                   2        /* BMP  */
#define dibosquechoque2                  3        /* BMP  */
#define dibosquesup                      4        /* BMP  */
#define dicasa                           5        /* BMP  */
#define dicasachoque                     6        /* BMP  */
#define dicasasup                        7        /* BMP  */
#define diciudad1                        8        /* BMP  */
#define diciudad1choque                  9        /* BMP  */
#define diciudad1sup                     10       /* BMP  */
#define dicursor                         11       /* BMP  */
#define diene001                         12       /* BMP  */
#define diespada                         13       /* BMP  */
#define dihamster                        14       /* BMP  */
#define dihamster0                       15       /* BMP  */
#define dihamster2                       16       /* BMP  */
#define diinventario                     17       /* BMP  */
#define dijefe01                         18       /* BMP  */
#define dijefe02                         19       /* BMP  */
#define dijefe03                         20       /* BMP  */
#define dilanza                          21       /* BMP  */
#define dilvup                           22       /* BMP  */
#define dimenu                           23       /* BMP  */
#define dimenu2                          24       /* BMP  */
#define diobj01                          25       /* BMP  */
#define diobj02                          26       /* BMP  */
#define diobj03                          27       /* BMP  */
#define diobj04                          28       /* BMP  */
#define diobj05                          29       /* BMP  */
#define diobj06                          30       /* BMP  */
#define diobj07                          31       /* BMP  */
#define diobj08                          32       /* BMP  */
#define diobj09                          33       /* BMP  */
#define diper001                         34       /* BMP  */
#define diper002                         35       /* BMP  */
#define diper003                         36       /* BMP  */
#define diper004                         37       /* BMP  */
#define diper005                         38       /* BMP  */
#define diper006                         39       /* BMP  */
#define diper007                         40       /* BMP  */
#define diper008                         41       /* BMP  */
#define ditienda1                        42       /* BMP  */
#define ditienda1choque                  43       /* BMP  */
#define ditienda1sup                     44       /* BMP  */
#define dmbatalla                        45       /* MIDI */
#define dmbosque                         46       /* MIDI */
#define dmcasa                           47       /* MIDI */
#define dmciudad                         48       /* MIDI */
#define dmmenu                           49       /* MIDI */
#define dsaa                             50       /* SAMP */
#define dsabrir_puerta                   51       /* SAMP */
#define dsbosque                         52       /* SAMP */
#define dsboton1                         53       /* SAMP */
#define dsboton2                         54       /* SAMP */
#define dserror                          55       /* SAMP */
#define dsespada1                        56       /* SAMP */
#define dsespada2                        57       /* SAMP */
#define dsespada3                        58       /* SAMP */
#define dsmuerte01                       59       /* SAMP */
#define dspasos                          60       /* SAMP */
#define dssubedenivel                    61       /* SAMP */

